# application-oracle.yaml
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: spring
    password: spring
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect